base_image: {{ env["RAY_IMAGE_NIGHTLY_CPU"] }}
env_vars: {"RAY_lineage_pinning_enabled": "1"}
debian_packages: []

python:
  pip_packages: ["dask[complete]", tqdm, scipy, xarray, zarr, pyarrow]
  conda_packages: []

post_build_cmds:
  # - uv pip install --system fastparquet
  - uv pip install --system boto3 s3fs
  - pip3 uninstall -y ray && uv pip install --system -U {{ env["RAY_WHEELS"] | default("ray") }}
  - uv pip install --system ray[default]
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
